# SlantUI: the palettes, the metrics and the band, as data.
#
# Written by `python -m slantui.tokens ps1 -o PATH` from
# slantui/tokens/palettes.py, slantui/tokens/metrics.py and
# slantui/geometry.py. Nothing here is written by hand.
#
# Read it with Import-PowerShellDataFile, or let the module do it:
#
#     Import-Module .\SlantUI.psm1
#     $p = Get-SlantPalette 'gold-dark'
#     $b = Get-SlantBrushes 'gold-dark'
#     $window.Background = $b['surface-0']
#
# Values holds the CSS hex a stylesheet would carry, Wpf the same colour with
# the alpha moved to the front, which is the form WPF parses.

@{
    Default  = 'gold-dark'

    # The role vocabulary, in the order the library lists it.
    Roles = @(
        'surface-0'
        'surface-1'
        'surface-2'
        'surface-3'
        'control'
        'control-hover'
        'control-active'
        'text-1'
        'text-2'
        'text-3'
        'text-4'
        'accent'
        'accent-hover'
        'accent-active'
        'on-accent'
        'accent-text'
        'accent-surface'
        'accent-surface-hover'
        'ok'
        'warn'
        'err'
        'on-status'
        'ok-text'
        'warn-text'
        'err-text'
        'warn-surface'
        'err-surface'
        'err-surface-hover'
        'scrim'
        'shadow'
        'overlay'
    )

    # Lengths carry their unit, the way the stylesheet writes
    # them. MetricNumbers is the same set with the unit taken off.
    Metrics = @{
        'r-xs'                   = '4px'
        'r'                      = '5px'
        'r-md'                   = '6px'
        'r-lg'                   = '7px'
        'r-pill'                 = '99px'
        'sp-1'                   = '4px'
        'sp-2'                   = '8px'
        'sp-3'                   = '12px'
        'font'                   = '''Segoe UI'',system-ui,-apple-system,sans-serif'
        'font-brand'             = '''Abadi'',''Abadi MT Std'',''Segoe UI Variable Display'',''Selawik'',''Segoe UI'',system-ui,sans-serif'
        'font-credit'            = '''Segoe UI Variable Text'',''Segoe UI'',system-ui,sans-serif'
        'mono'                   = 'Consolas,''Courier New'',monospace'
        'fs'                     = '12.5px'
        'fs-sm'                  = '11.5px'
        'fs-xs'                  = '10px'
        'fs-lg'                  = '13.5px'
        'fs-brand'               = '14.5px'
        'fs-credit'              = '11px'
        'ls-brand'               = '.15px'
        'ls-strong'              = '.4px'
        'ls-credit'              = '.25px'
        'w'                      = '400'
        'w-strong'               = '600'
        'lh'                     = '1.45'
        'tbar-h'                 = '44px'
        'tbar-thin'              = '28px'
        'tbar-slant'             = '38px'
        'tbar-join'              = '8px'
        'tbar-mark'              = '22px'
        'tbar-mark-gap'          = '14px'
        'tbar-name-end'          = '16px'
        'tbar-ring'              = '4px'
        'tbar-lift'              = '1px'
        'tbar-lift-blur'         = '3px'
        'tbar-button'            = '42px'
        'tbar-glyph'             = '12px'
        'tbar-stroke'            = '1.35'
        'rz'                     = '5px'
        'rz-corner'              = '12px'
        'tab-h'                  = '42px'
        'tab-w'                  = '132px'
        'rp-w'                   = '244px'
        'slot'                   = '32px'
        'block'                  = '96px'
        'blur'                   = '14px'
        'sheet-w'                = '520px'
        'sheet-wide'             = '660px'
        't-in'                   = '120ms'
        't-out'                  = '180ms'
        't-chg'                  = '140ms'
        't-reveal'               = '1600ms'
    }
    MetricNumbers = @{
        'r-xs'                   = 4
        'r'                      = 5
        'r-md'                   = 6
        'r-lg'                   = 7
        'r-pill'                 = 99
        'sp-1'                   = 4
        'sp-2'                   = 8
        'sp-3'                   = 12
        'fs'                     = 12.5
        'fs-sm'                  = 11.5
        'fs-xs'                  = 10
        'fs-lg'                  = 13.5
        'fs-brand'               = 14.5
        'fs-credit'              = 11
        'ls-brand'               = 0.15
        'ls-strong'              = 0.4
        'ls-credit'              = 0.25
        'tbar-h'                 = 44
        'tbar-thin'              = 28
        'tbar-slant'             = 38
        'tbar-join'              = 8
        'tbar-mark'              = 22
        'tbar-mark-gap'          = 14
        'tbar-name-end'          = 16
        'tbar-ring'              = 4
        'tbar-lift'              = 1
        'tbar-lift-blur'         = 3
        'tbar-button'            = 42
        'tbar-glyph'             = 12
        'rz'                     = 5
        'rz-corner'              = 12
        'tab-h'                  = 42
        'tab-w'                  = 132
        'rp-w'                   = 244
        'slot'                   = 32
        'block'                  = 96
        'blur'                   = 14
        'sheet-w'                = 520
        'sheet-wide'             = 660
    }
    # Plain numbers: weights, a line height, a stroke width.
    Numbers = @{
        'w'                      = 400
        'w-strong'               = 600
        'lh'                     = 1.45
        'tbar-stroke'            = 1.35
    }
    # Durations in milliseconds, for a storyboard or a timer.
    Times = @{
        't-in'                   = 120
        't-out'                  = 180
        't-chg'                  = 140
        't-reveal'               = 1600
    }
    Fonts = @{
        'font'                   = 'Segoe UI'
        'font-brand'             = 'Abadi, Abadi MT Std, Segoe UI Variable Display, Selawik, Segoe UI'
        'font-credit'            = 'Segoe UI Variable Text, Segoe UI'
        'mono'                   = 'Consolas, Courier New'
    }

    # The role each part of the title band is in, read out of the rule
    # the page uses for it (slantui.css.BAND_PARTS).
    BandRoles = @{
        'band'                   = 'control'
        'name'                   = 'text-2'
        'strong'                 = 'text-1'
        'credit'                 = 'text-4'
        'disc'                   = 'control-hover'
        'disc-hover'             = 'accent-surface-hover'
        'disc-down'              = 'accent-surface'
        'lift'                   = 'shadow'
        'glyph'                  = 'text-3'
        'hover'                  = 'control-hover'
        'hover-glyph'            = 'text-1'
        'close'                  = 'err'
        'close-glyph'            = 'on-status'
        'strip'                  = 'surface-0'
    }

    # The four numbers the oblique band is built from.
    Band = @{
        Height = 44
        Thin   = 28
        Slant  = 38
        Join   = 8
        Drop   = 16
        Angle  = 22.8337
    }

    Palettes = @{
        'gold-dark' = @{
            Name   = 'Gold Dark'
            Scheme = 'dark'
            Note   = 'Gold on near black. It''s the palette the design was drawn in.'
            Values = @{
                'surface-0'            = '#0D0D0F'
                'surface-1'            = '#101013'
                'surface-2'            = '#121216'
                'surface-3'            = '#16161B'
                'control'              = '#1E1E24'
                'control-hover'        = '#33333B'
                'control-active'       = '#26262B'
                'text-1'               = '#E6E6EC'
                'text-2'               = '#C8C8D0'
                'text-3'               = '#A0A0AA'
                'text-4'               = '#80808A'
                'accent'               = '#F5C542'
                'accent-hover'         = '#FFD45E'
                'accent-active'        = '#C9A033'
                'on-accent'            = '#0D0D0F'
                'accent-text'          = '#F5C542'
                'accent-surface'       = '#2A2519'
                'accent-surface-hover' = '#332C1D'
                'ok'                   = '#2F7A46'
                'warn'                 = '#8F6410'
                'err'                  = '#B0524A'
                'on-status'            = '#FFFFFF'
                'ok-text'              = '#58B36B'
                'warn-text'            = '#E0A93C'
                'err-text'             = '#F77D67'
                'warn-surface'         = '#282218'
                'err-surface'          = '#2C1F1E'
                'err-surface-hover'    = '#3A2724'
                'scrim'                = '#0D0D0FB8'
                'shadow'               = '#00000099'
                'overlay'              = '#101013F2'
            }
            Wpf = @{
                'surface-0'            = '#0D0D0F'
                'surface-1'            = '#101013'
                'surface-2'            = '#121216'
                'surface-3'            = '#16161B'
                'control'              = '#1E1E24'
                'control-hover'        = '#33333B'
                'control-active'       = '#26262B'
                'text-1'               = '#E6E6EC'
                'text-2'               = '#C8C8D0'
                'text-3'               = '#A0A0AA'
                'text-4'               = '#80808A'
                'accent'               = '#F5C542'
                'accent-hover'         = '#FFD45E'
                'accent-active'        = '#C9A033'
                'on-accent'            = '#0D0D0F'
                'accent-text'          = '#F5C542'
                'accent-surface'       = '#2A2519'
                'accent-surface-hover' = '#332C1D'
                'ok'                   = '#2F7A46'
                'warn'                 = '#8F6410'
                'err'                  = '#B0524A'
                'on-status'            = '#FFFFFF'
                'ok-text'              = '#58B36B'
                'warn-text'            = '#E0A93C'
                'err-text'             = '#F77D67'
                'warn-surface'         = '#282218'
                'err-surface'          = '#2C1F1E'
                'err-surface-hover'    = '#3A2724'
                'scrim'                = '#B80D0D0F'
                'shadow'               = '#99000000'
                'overlay'              = '#F2101013'
            }
        }
        'gold-light' = @{
            Name   = 'Gold Light'
            Scheme = 'light'
            Note   = 'The same gold on paper. The surfaces and the text are the ones a printed report uses.'
            Values = @{
                'surface-0'            = '#EFEFF2'
                'surface-1'            = '#F1F1F4'
                'surface-2'            = '#F7F7F9'
                'surface-3'            = '#FFFFFF'
                'control'              = '#DDDDE0'
                'control-hover'        = '#CECED1'
                'control-active'       = '#D6D6D9'
                'text-1'               = '#17171B'
                'text-2'               = '#3B3C40'
                'text-3'               = '#545458'
                'text-4'               = '#6E6E73'
                'accent'               = '#F5C542'
                'accent-hover'         = '#E4B52B'
                'accent-active'        = '#D2A300'
                'on-accent'            = '#17171B'
                'accent-text'          = '#764A00'
                'accent-surface'       = '#FFF8E4'
                'accent-surface-hover' = '#FCEFCD'
                'ok'                   = '#2F7A46'
                'warn'                 = '#8F6410'
                'err'                  = '#B0524A'
                'on-status'            = '#FFFFFF'
                'ok-text'              = '#0F612F'
                'warn-text'            = '#7F4600'
                'err-text'             = '#913630'
                'warn-surface'         = '#F2EBE0'
                'err-surface'          = '#F7E8E8'
                'err-surface-hover'    = '#F1DCDC'
                'scrim'                = '#EFEFF2B8'
                'shadow'               = '#00000038'
                'overlay'              = '#F1F1F4F2'
            }
            Wpf = @{
                'surface-0'            = '#EFEFF2'
                'surface-1'            = '#F1F1F4'
                'surface-2'            = '#F7F7F9'
                'surface-3'            = '#FFFFFF'
                'control'              = '#DDDDE0'
                'control-hover'        = '#CECED1'
                'control-active'       = '#D6D6D9'
                'text-1'               = '#17171B'
                'text-2'               = '#3B3C40'
                'text-3'               = '#545458'
                'text-4'               = '#6E6E73'
                'accent'               = '#F5C542'
                'accent-hover'         = '#E4B52B'
                'accent-active'        = '#D2A300'
                'on-accent'            = '#17171B'
                'accent-text'          = '#764A00'
                'accent-surface'       = '#FFF8E4'
                'accent-surface-hover' = '#FCEFCD'
                'ok'                   = '#2F7A46'
                'warn'                 = '#8F6410'
                'err'                  = '#B0524A'
                'on-status'            = '#FFFFFF'
                'ok-text'              = '#0F612F'
                'warn-text'            = '#7F4600'
                'err-text'             = '#913630'
                'warn-surface'         = '#F2EBE0'
                'err-surface'          = '#F7E8E8'
                'err-surface-hover'    = '#F1DCDC'
                'scrim'                = '#B8EFEFF2'
                'shadow'               = '#38000000'
                'overlay'              = '#F2F1F1F4'
            }
        }
        'teal-dark' = @{
            Name   = 'Teal Dark'
            Scheme = 'dark'
            Note   = 'Gold Dark with a teal accent in front.'
            Values = @{
                'surface-0'            = '#0D0D0F'
                'surface-1'            = '#101013'
                'surface-2'            = '#121216'
                'surface-3'            = '#16161B'
                'control'              = '#1E1E24'
                'control-hover'        = '#33333B'
                'control-active'       = '#26262B'
                'text-1'               = '#E6E6EC'
                'text-2'               = '#C8C8D0'
                'text-3'               = '#A0A0AA'
                'text-4'               = '#80808A'
                'accent'               = '#3FBFB0'
                'accent-hover'         = '#55D1C1'
                'accent-active'        = '#14A697'
                'on-accent'            = '#0D0D0F'
                'accent-text'          = '#3FBFB0'
                'accent-surface'       = '#1D2428'
                'accent-surface-hover' = '#202C2F'
                'ok'                   = '#2F7A46'
                'warn'                 = '#8F6410'
                'err'                  = '#B0524A'
                'on-status'            = '#FFFFFF'
                'ok-text'              = '#58B36B'
                'warn-text'            = '#E0A93C'
                'err-text'             = '#F77D67'
                'warn-surface'         = '#282218'
                'err-surface'          = '#2C1F1E'
                'err-surface-hover'    = '#3A2724'
                'scrim'                = '#0D0D0FB8'
                'shadow'               = '#00000099'
                'overlay'              = '#101013F2'
            }
            Wpf = @{
                'surface-0'            = '#0D0D0F'
                'surface-1'            = '#101013'
                'surface-2'            = '#121216'
                'surface-3'            = '#16161B'
                'control'              = '#1E1E24'
                'control-hover'        = '#33333B'
                'control-active'       = '#26262B'
                'text-1'               = '#E6E6EC'
                'text-2'               = '#C8C8D0'
                'text-3'               = '#A0A0AA'
                'text-4'               = '#80808A'
                'accent'               = '#3FBFB0'
                'accent-hover'         = '#55D1C1'
                'accent-active'        = '#14A697'
                'on-accent'            = '#0D0D0F'
                'accent-text'          = '#3FBFB0'
                'accent-surface'       = '#1D2428'
                'accent-surface-hover' = '#202C2F'
                'ok'                   = '#2F7A46'
                'warn'                 = '#8F6410'
                'err'                  = '#B0524A'
                'on-status'            = '#FFFFFF'
                'ok-text'              = '#58B36B'
                'warn-text'            = '#E0A93C'
                'err-text'             = '#F77D67'
                'warn-surface'         = '#282218'
                'err-surface'          = '#2C1F1E'
                'err-surface-hover'    = '#3A2724'
                'scrim'                = '#B80D0D0F'
                'shadow'               = '#99000000'
                'overlay'              = '#F2101013'
            }
        }
        'blue-dark' = @{
            Name   = 'Blue Dark'
            Scheme = 'dark'
            Note   = 'Gold Dark with a blue accent in front.'
            Values = @{
                'surface-0'            = '#0D0D0F'
                'surface-1'            = '#101013'
                'surface-2'            = '#121216'
                'surface-3'            = '#16161B'
                'control'              = '#1E1E24'
                'control-hover'        = '#33333B'
                'control-active'       = '#26262B'
                'text-1'               = '#E6E6EC'
                'text-2'               = '#C8C8D0'
                'text-3'               = '#A0A0AA'
                'text-4'               = '#80808A'
                'accent'               = '#5B8DEF'
                'accent-hover'         = '#6B9EFF'
                'accent-active'        = '#4A7ADB'
                'on-accent'            = '#0D0D0F'
                'accent-text'          = '#6CA0FF'
                'accent-surface'       = '#1D212D'
                'accent-surface-hover' = '#202737'
                'ok'                   = '#2F7A46'
                'warn'                 = '#8F6410'
                'err'                  = '#B0524A'
                'on-status'            = '#FFFFFF'
                'ok-text'              = '#58B36B'
                'warn-text'            = '#E0A93C'
                'err-text'             = '#F77D67'
                'warn-surface'         = '#282218'
                'err-surface'          = '#2C1F1E'
                'err-surface-hover'    = '#3A2724'
                'scrim'                = '#0D0D0FB8'
                'shadow'               = '#00000099'
                'overlay'              = '#101013F2'
            }
            Wpf = @{
                'surface-0'            = '#0D0D0F'
                'surface-1'            = '#101013'
                'surface-2'            = '#121216'
                'surface-3'            = '#16161B'
                'control'              = '#1E1E24'
                'control-hover'        = '#33333B'
                'control-active'       = '#26262B'
                'text-1'               = '#E6E6EC'
                'text-2'               = '#C8C8D0'
                'text-3'               = '#A0A0AA'
                'text-4'               = '#80808A'
                'accent'               = '#5B8DEF'
                'accent-hover'         = '#6B9EFF'
                'accent-active'        = '#4A7ADB'
                'on-accent'            = '#0D0D0F'
                'accent-text'          = '#6CA0FF'
                'accent-surface'       = '#1D212D'
                'accent-surface-hover' = '#202737'
                'ok'                   = '#2F7A46'
                'warn'                 = '#8F6410'
                'err'                  = '#B0524A'
                'on-status'            = '#FFFFFF'
                'ok-text'              = '#58B36B'
                'warn-text'            = '#E0A93C'
                'err-text'             = '#F77D67'
                'warn-surface'         = '#282218'
                'err-surface'          = '#2C1F1E'
                'err-surface-hover'    = '#3A2724'
                'scrim'                = '#B80D0D0F'
                'shadow'               = '#99000000'
                'overlay'              = '#F2101013'
            }
        }
        'purple-dark' = @{
            Name   = 'Purple Dark'
            Scheme = 'dark'
            Note   = 'Gold Dark with a purple accent in front.'
            Values = @{
                'surface-0'            = '#0D0D0F'
                'surface-1'            = '#101013'
                'surface-2'            = '#121216'
                'surface-3'            = '#16161B'
                'control'              = '#1E1E24'
                'control-hover'        = '#33333B'
                'control-active'       = '#26262B'
                'text-1'               = '#E6E6EC'
                'text-2'               = '#C8C8D0'
                'text-3'               = '#A0A0AA'
                'text-4'               = '#80808A'
                'accent'               = '#B07CF0'
                'accent-hover'         = '#C18DFF'
                'accent-active'        = '#9763D5'
                'on-accent'            = '#0D0D0F'
                'accent-text'          = '#BC88FD'
                'accent-surface'       = '#231F2D'
                'accent-surface-hover' = '#2A2537'
                'ok'                   = '#2F7A46'
                'warn'                 = '#8F6410'
                'err'                  = '#B0524A'
                'on-status'            = '#FFFFFF'
                'ok-text'              = '#58B36B'
                'warn-text'            = '#E0A93C'
                'err-text'             = '#F77D67'
                'warn-surface'         = '#282218'
                'err-surface'          = '#2C1F1E'
                'err-surface-hover'    = '#3A2724'
                'scrim'                = '#0D0D0FB8'
                'shadow'               = '#00000099'
                'overlay'              = '#101013F2'
            }
            Wpf = @{
                'surface-0'            = '#0D0D0F'
                'surface-1'            = '#101013'
                'surface-2'            = '#121216'
                'surface-3'            = '#16161B'
                'control'              = '#1E1E24'
                'control-hover'        = '#33333B'
                'control-active'       = '#26262B'
                'text-1'               = '#E6E6EC'
                'text-2'               = '#C8C8D0'
                'text-3'               = '#A0A0AA'
                'text-4'               = '#80808A'
                'accent'               = '#B07CF0'
                'accent-hover'         = '#C18DFF'
                'accent-active'        = '#9763D5'
                'on-accent'            = '#0D0D0F'
                'accent-text'          = '#BC88FD'
                'accent-surface'       = '#231F2D'
                'accent-surface-hover' = '#2A2537'
                'ok'                   = '#2F7A46'
                'warn'                 = '#8F6410'
                'err'                  = '#B0524A'
                'on-status'            = '#FFFFFF'
                'ok-text'              = '#58B36B'
                'warn-text'            = '#E0A93C'
                'err-text'             = '#F77D67'
                'warn-surface'         = '#282218'
                'err-surface'          = '#2C1F1E'
                'err-surface-hover'    = '#3A2724'
                'scrim'                = '#B80D0D0F'
                'shadow'               = '#99000000'
                'overlay'              = '#F2101013'
            }
        }
        'green-dark' = @{
            Name   = 'Green Dark'
            Scheme = 'dark'
            Note   = 'Gold Dark with a green accent in front. The accent and the ok colour share a hue here, so read the shape, not the colour.'
            Values = @{
                'surface-0'            = '#0D0D0F'
                'surface-1'            = '#101013'
                'surface-2'            = '#121216'
                'surface-3'            = '#16161B'
                'control'              = '#1E1E24'
                'control-hover'        = '#33333B'
                'control-active'       = '#26262B'
                'text-1'               = '#E6E6EC'
                'text-2'               = '#C8C8D0'
                'text-3'               = '#A0A0AA'
                'text-4'               = '#80808A'
                'accent'               = '#57B26A'
                'accent-hover'         = '#69C47B'
                'accent-active'        = '#3C9952'
                'on-accent'            = '#0D0D0F'
                'accent-text'          = '#58B36B'
                'accent-surface'       = '#1D2323'
                'accent-surface-hover' = '#212B27'
                'ok'                   = '#2F7A46'
                'warn'                 = '#8F6410'
                'err'                  = '#B0524A'
                'on-status'            = '#FFFFFF'
                'ok-text'              = '#58B36B'
                'warn-text'            = '#E0A93C'
                'err-text'             = '#F77D67'
                'warn-surface'         = '#282218'
                'err-surface'          = '#2C1F1E'
                'err-surface-hover'    = '#3A2724'
                'scrim'                = '#0D0D0FB8'
                'shadow'               = '#00000099'
                'overlay'              = '#101013F2'
            }
            Wpf = @{
                'surface-0'            = '#0D0D0F'
                'surface-1'            = '#101013'
                'surface-2'            = '#121216'
                'surface-3'            = '#16161B'
                'control'              = '#1E1E24'
                'control-hover'        = '#33333B'
                'control-active'       = '#26262B'
                'text-1'               = '#E6E6EC'
                'text-2'               = '#C8C8D0'
                'text-3'               = '#A0A0AA'
                'text-4'               = '#80808A'
                'accent'               = '#57B26A'
                'accent-hover'         = '#69C47B'
                'accent-active'        = '#3C9952'
                'on-accent'            = '#0D0D0F'
                'accent-text'          = '#58B36B'
                'accent-surface'       = '#1D2323'
                'accent-surface-hover' = '#212B27'
                'ok'                   = '#2F7A46'
                'warn'                 = '#8F6410'
                'err'                  = '#B0524A'
                'on-status'            = '#FFFFFF'
                'ok-text'              = '#58B36B'
                'warn-text'            = '#E0A93C'
                'err-text'             = '#F77D67'
                'warn-surface'         = '#282218'
                'err-surface'          = '#2C1F1E'
                'err-surface-hover'    = '#3A2724'
                'scrim'                = '#B80D0D0F'
                'shadow'               = '#99000000'
                'overlay'              = '#F2101013'
            }
        }
        'slate-light' = @{
            Name   = 'Slate Light'
            Scheme = 'light'
            Note   = 'Cool greys and a blue accent, for an application that should not look like the default.'
            Values = @{
                'surface-0'            = '#E9EBEF'
                'surface-1'            = '#EDEFF3'
                'surface-2'            = '#F1F3F7'
                'surface-3'            = '#F5F7FB'
                'control'              = '#D7D9DD'
                'control-hover'        = '#C8CACE'
                'control-active'       = '#D0D2D6'
                'text-1'               = '#1A1C22'
                'text-2'               = '#373940'
                'text-3'               = '#4F5159'
                'text-4'               = '#696C73'
                'accent'               = '#3B72D9'
                'accent-hover'         = '#2D62C8'
                'accent-active'        = '#1C52B6'
                'on-accent'            = '#FFFFFF'
                'accent-text'          = '#164BAF'
                'accent-surface'       = '#E2EAF9'
                'accent-surface-hover' = '#D7E3F8'
                'ok'                   = '#2F7A46'
                'warn'                 = '#8F6410'
                'err'                  = '#AB4E46'
                'on-status'            = '#FFFFFF'
                'ok-text'              = '#095E2C'
                'warn-text'            = '#7C4300'
                'err-text'             = '#8E332E'
                'warn-surface'         = '#EBE5DD'
                'err-surface'          = '#EEE3E5'
                'err-surface-hover'    = '#EBD9DA'
                'scrim'                = '#E9EBEFB8'
                'shadow'               = '#00000038'
                'overlay'              = '#EDEFF3F2'
            }
            Wpf = @{
                'surface-0'            = '#E9EBEF'
                'surface-1'            = '#EDEFF3'
                'surface-2'            = '#F1F3F7'
                'surface-3'            = '#F5F7FB'
                'control'              = '#D7D9DD'
                'control-hover'        = '#C8CACE'
                'control-active'       = '#D0D2D6'
                'text-1'               = '#1A1C22'
                'text-2'               = '#373940'
                'text-3'               = '#4F5159'
                'text-4'               = '#696C73'
                'accent'               = '#3B72D9'
                'accent-hover'         = '#2D62C8'
                'accent-active'        = '#1C52B6'
                'on-accent'            = '#FFFFFF'
                'accent-text'          = '#164BAF'
                'accent-surface'       = '#E2EAF9'
                'accent-surface-hover' = '#D7E3F8'
                'ok'                   = '#2F7A46'
                'warn'                 = '#8F6410'
                'err'                  = '#AB4E46'
                'on-status'            = '#FFFFFF'
                'ok-text'              = '#095E2C'
                'warn-text'            = '#7C4300'
                'err-text'             = '#8E332E'
                'warn-surface'         = '#EBE5DD'
                'err-surface'          = '#EEE3E5'
                'err-surface-hover'    = '#EBD9DA'
                'scrim'                = '#B8E9EBEF'
                'shadow'               = '#38000000'
                'overlay'              = '#F2EDEFF3'
            }
        }
        'high-contrast' = @{
            Name   = 'High Contrast'
            Scheme = 'dark'
            Note   = 'Pure black, pure white, saturated accents. Nothing in it is near a threshold, and the surfaces are far enough apart to be told apart without a divider.'
            Values = @{
                'surface-0'            = '#000000'
                'surface-1'            = '#0A0A0A'
                'surface-2'            = '#141414'
                'surface-3'            = '#1E1E1E'
                'control'              = '#2B2B2B'
                'control-hover'        = '#3D3D3D'
                'control-active'       = '#333333'
                'text-1'               = '#FFFFFF'
                'text-2'               = '#F0F0F0'
                'text-3'               = '#DCDCDC'
                'text-4'               = '#B4B4B4'
                'accent'               = '#FFD400'
                'accent-hover'         = '#FFE44A'
                'accent-active'        = '#D9B400'
                'on-accent'            = '#000000'
                'accent-text'          = '#FFD400'
                'accent-surface'       = '#332B00'
                'accent-surface-hover' = '#4A3E00'
                'ok'                   = '#0A6B28'
                'warn'                 = '#8A5200'
                'err'                  = '#A81E16'
                'on-status'            = '#FFFFFF'
                'ok-text'              = '#3FD174'
                'warn-text'            = '#FFB020'
                'err-text'             = '#FF9080'
                'warn-surface'         = '#351700'
                'err-surface'          = '#3A0F0C'
                'err-surface-hover'    = '#4F1612'
                'scrim'                = '#000000CC'
                'shadow'               = '#000000B3'
                'overlay'              = '#000000F2'
            }
            Wpf = @{
                'surface-0'            = '#000000'
                'surface-1'            = '#0A0A0A'
                'surface-2'            = '#141414'
                'surface-3'            = '#1E1E1E'
                'control'              = '#2B2B2B'
                'control-hover'        = '#3D3D3D'
                'control-active'       = '#333333'
                'text-1'               = '#FFFFFF'
                'text-2'               = '#F0F0F0'
                'text-3'               = '#DCDCDC'
                'text-4'               = '#B4B4B4'
                'accent'               = '#FFD400'
                'accent-hover'         = '#FFE44A'
                'accent-active'        = '#D9B400'
                'on-accent'            = '#000000'
                'accent-text'          = '#FFD400'
                'accent-surface'       = '#332B00'
                'accent-surface-hover' = '#4A3E00'
                'ok'                   = '#0A6B28'
                'warn'                 = '#8A5200'
                'err'                  = '#A81E16'
                'on-status'            = '#FFFFFF'
                'ok-text'              = '#3FD174'
                'warn-text'            = '#FFB020'
                'err-text'             = '#FF9080'
                'warn-surface'         = '#351700'
                'err-surface'          = '#3A0F0C'
                'err-surface-hover'    = '#4F1612'
                'scrim'                = '#CC000000'
                'shadow'               = '#B3000000'
                'overlay'              = '#F2000000'
            }
        }
    }
}
